services:

    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    App\Http\:
        resource: '%kernel.project_dir%/src/Http/*'

    App\Http\ApiKey:
        arguments:
            - '%api_key%'
