services:

    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    App\Passwords\:
        resource: '%kernel.project_dir%/src/Passwords/*'

    App\Passwords\PasswordSettings:
        arguments:
            - '%active_algorithm%'
            - '%bcrypt_cost%'
            - '%argon_time_cost%'
            - '%argon_memory_cost%'
