services:

    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    App\RequestValidators\:
        resource: '%kernel.project_dir%/src/RequestValidators/*'

    App\RequestValidators\RequestValidator:
        arguments:
            - '%perform_request_validation%'
            - '@app.validators.missing_mandatory_api_key_http_header'
            - '@app.validators.missing_mandatory_api_client_id_http_header'
            - '@app.validators.missing_mandatory_api_token_http_header'
            - '@app.validators.missing_value_for_api_key_http_header'
            - '@app.validators.missing_value_for_api_client_id_http_header'
            - '@app.validators.missing_value_for_api_token_http_header'
            - '@app.validators.invalid_value_for_api_key_http_header'
            - '@app.validators.invalid_value_for_api_client_id_http_header'
            - '@app.validators.invalid_value_for_api_token_http_header'
            - '@app.validators.check_if_http_method_is_get'
            - '@app.validators.check_if_http_method_is_post'
            - '@app.validators.check_if_http_method_is_delete'
            - '@app.validators.check_if_http_method_is_patch'
            - '@app.validators.missing_mandatory_id_url_parameter'
            - '@app.validators.missing_mandatory_email_url_parameter'
            - '@app.validators.missing_mandatory_token_url_parameter'
            - '@app.validators.missing_value_for_id_url_parameter'
            - '@app.validators.missing_value_for_email_url_parameter'
            - '@app.validators.missing_value_for_token_url_parameter'
            - '@app.validators.no_data_found_for_course_id_url_parameter'
            - '@app.validators.no_data_found_for_lesson_id_url_parameter'
            - '@app.validators.no_data_found_for_email_url_parameter'
            - '@app.validators.no_data_found_for_token_url_parameter'
            - '@app.validators.user_not_found_by_email_credentials_in_url_parameters'
            - '@app.validators.missing_json_in_request_body'
            - '@app.validators.malformed_json_in_request_body'
            - '@app.validators.missing_mandatory_property_id_in_request_body'
            - '@app.validators.missing_mandatory_property_course_id_in_request_body'
            - '@app.validators.missing_mandatory_property_teacher_id_in_request_body'
            - '@app.validators.missing_mandatory_property_user_id_in_request_body'
            - '@app.validators.missing_mandatory_property_first_name_in_request_body'
            - '@app.validators.missing_mandatory_property_last_name_in_request_body'
            - '@app.validators.missing_mandatory_property_email_in_request_body'
            - '@app.validators.missing_mandatory_property_password_in_request_body'
            - '@app.validators.missing_mandatory_property_is_teacher_in_request_body'
            - '@app.validators.missing_mandatory_property_is_student_in_request_body'
            - '@app.validators.missing_mandatory_property_timezone_in_request_body'
            - '@app.validators.missing_mandatory_property_token_in_request_body'
            - '@app.validators.missing_mandatory_property_name_in_request_body'
            - '@app.validators.missing_mandatory_property_subject_in_request_body'
            - '@app.validators.missing_mandatory_property_from_in_request_body'
            - '@app.validators.missing_mandatory_property_to_in_request_body'
            - '@app.validators.missing_mandatory_property_old_api_client_id_in_request_body'
            - '@app.validators.missing_mandatory_property_security_code_in_request_body'
            - '@app.validators.missing_mandatory_property_is_active_in_request_body'
            - '@app.validators.missing_mandatory_property_price_in_request_body'
            - '@app.validators.expected_different_data_type_for_property_id_in_request_body'
            - '@app.validators.expected_different_data_type_for_property_course_id_in_request_body'
            - '@app.validators.expected_different_data_type_for_property_teacher_id_in_request_body'
            - '@app.validators.expected_different_data_type_for_property_user_id_in_request_body'
            - '@app.validators.expected_different_data_type_for_property_first_name_in_request_body'
            - '@app.validators.expected_different_data_type_for_property_last_name_in_request_body'
            - '@app.validators.expected_different_data_type_for_property_email_in_request_body'
            - '@app.validators.expected_different_data_type_for_property_password_in_request_body'
            - '@app.validators.expected_different_data_type_for_nullable_property_password_in_request_body'
            - '@app.validators.expected_different_data_type_for_property_is_teacher_in_request_body'
            - '@app.validators.expected_different_data_type_for_property_is_student_in_request_body'
            - '@app.validators.expected_different_data_type_for_property_timezone_in_request_body'
            - '@app.validators.expected_different_data_type_for_property_token_in_request_body'
            - '@app.validators.expected_different_data_type_for_property_name_in_request_body'
            - '@app.validators.expected_different_data_type_for_property_subject_in_request_body'
            - '@app.validators.expected_different_data_type_for_property_from_in_request_body'
            - '@app.validators.expected_different_data_type_for_property_to_in_request_body'
            - '@app.validators.expected_different_data_type_for_property_old_api_client_id_in_request_body'
            - '@app.validators.expected_different_data_type_for_property_security_code_in_request_body'
            - '@app.validators.expected_different_data_type_for_property_is_active_in_request_body'
            - '@app.validators.expected_number_for_property_price_in_request_body'
            - '@app.validators.expected_number_or_null_for_property_price_in_request_body'
            - '@app.validators.expected_non_empty_string_in_id_in_request_body'
            - '@app.validators.expected_non_empty_string_in_course_id_in_request_body'
            - '@app.validators.expected_non_empty_string_in_teacher_id_in_request_body'
            - '@app.validators.expected_non_empty_string_in_user_id_in_request_body'
            - '@app.validators.expected_non_empty_string_in_first_name_in_request_body'
            - '@app.validators.expected_non_empty_string_in_last_name_in_request_body'
            - '@app.validators.expected_non_empty_string_in_email_in_request_body'
            - '@app.validators.expected_non_empty_string_in_password_in_request_body'
            - '@app.validators.expected_non_empty_string_or_null_in_password_in_request_body'
            - '@app.validators.expected_non_empty_string_in_timezone_in_request_body'
            - '@app.validators.expected_non_empty_string_in_token_in_request_body'
            - '@app.validators.expected_non_empty_string_in_name_in_request_body'
            - '@app.validators.expected_non_empty_string_in_subject_in_request_body'
            - '@app.validators.expected_non_empty_string_in_from_in_request_body'
            - '@app.validators.expected_non_empty_string_in_to_in_request_body'
            - '@app.validators.expected_non_empty_string_in_old_api_client_id_in_request_body'
            - '@app.validators.expected_non_empty_string_in_security_code_in_request_body'
            - '@app.validators.no_data_found_in_courses_for_property_course_id_in_request_body'
            - '@app.validators.no_data_found_in_users_for_property_user_id_in_request_body'
            - '@app.validators.no_data_found_for_property_course_id_in_request_body'
            - '@app.validators.no_data_found_for_property_lesson_id_in_request_body'
            - '@app.validators.no_data_found_for_property_teacher_id_in_request_body'
            - '@app.validators.no_data_found_for_property_email_in_request_body'
            - '@app.validators.no_data_found_for_property_user_id_in_request_body'
            - '@app.validators.user_not_found_by_credentials'
            - '@app.validators.user_not_found_by_email_credentials'
            - '@app.validators.numeric_value_in_price_must_be_greater_than_zero_in_request_body'
            - '@app.validators.numeric_value_in_price_must_be_greater_than_zero_or_null_in_request_body'
            - '@app.validators.malformed_email_in_url_parameter'
            - '@app.validators.malformed_email_in_request_body'
            - '@app.validators.malformed_date_time_in_property_from_in_request_body'
            - '@app.validators.malformed_date_time_in_property_to_in_request_body'
            - '@app.validators.token_expired'
            - '@app.validators.token_in_url_parameter_expired'
            - '@app.validators.malformed_uuid_for_property_id_in_request_body'
            - '@app.validators.malformed_uuid_for_property_course_id_in_request_body'
            - '@app.validators.malformed_uuid_for_property_teacher_id_in_request_body'
            - '@app.validators.malformed_uuid_in_id_url_parameter'
            - '@app.validators.given_date_time_does_not_make_any_sense_in_property_from_in_request_body'
            - '@app.validators.given_date_time_does_not_make_any_sense_in_property_to_in_request_body'
            - '@app.validators.date_time_in_from_cannot_be_greater_or_equal_to_date_time_in_to'
            - '@app.validators.selected_user_is_not_teacher'
            - '@app.validators.user_is_not_teacher_so_price_must_not_be_set'
            - '@app.validators.user_is_teacher_so_price_must_be_set'
            - '@app.validators.cannot_subscribe_to_inactive_course'
            - '@app.validators.cannot_subscribe_to_ongoing_or_ended_course'
            - '@app.validators.cannot_unsubscribe_from_ongoing_or_ended_course'
            - '@app.validators.to_accept_this_request_the_user_has_to_be_teacher'
            - '@app.validators.to_delete_the_lesson_the_user_has_to_be_teacher'
            - '@app.validators.to_delete_the_course_the_user_has_to_be_teacher'
            - '@app.validators.cannot_delete_lesson_from_ongoing_or_ended_course'
            - '@app.validators.cannot_delete_ongoing_or_ended_course'
            - '@app.validators.attempt_to_log_into_an_unconfirmed_user_account'
            - '@app.validators.cannot_delete_teacher_with_ongoing_courses'
            - '@app.validators.cannot_delete_student_which_is_subscribed_to_ongoing_courses'
            - '@app.validators.session_found_by_api_token_but_its_client_id_does_not_match'
            - '@app.validators.session_is_locked'
            - '@app.validators.incorrect_password_has_been_entered'
            - '@app.validators.account_has_been_locked'
            - '@app.validators.security_code_has_been_generated'
            - '@app.validators.incorrect_security_code_has_been_entered'
            - '@app.validators.security_code_has_been_generated_again'
            - '@app.validators.security_code_has_expired'
            - '@app.validators.user_is_trying_to_use_another_email_address'
            - '@app.validators.old_api_client_id_is_different_than_the_one_in_current_session'
            - '@app.validators.user_does_not_have_any_security_code'
            - '@app.validators.cannot_subscribe_to_your_own_course'
            - '@app.validators.cannot_unsubscribe_from_course_to_which_you_are_not_subscribed_to'
            - '@app.validators.to_update_the_lesson_the_user_has_to_be_teacher'
            - '@app.validators.to_update_the_course_the_user_has_to_be_teacher'
            - '@app.validators.cannot_update_lesson_from_ongoing_or_ended_course'
            - '@app.validators.cannot_update_ongoing_or_ended_course'
            - '@app.validators.string_length_must_not_be_longer_for_property_first_name_in_request_body'
            - '@app.validators.string_length_must_not_be_longer_for_property_last_name_in_request_body'
            - '@app.validators.string_length_must_not_be_longer_for_property_email_in_request_body'
            - '@app.validators.string_length_must_not_be_longer_for_property_name_in_request_body'
            - '@app.validators.string_length_must_not_be_longer_for_property_subject_in_request_body'
            - '@app.validators.number_size_must_not_be_higher_for_property_price_in_request_body'
            - '@app.validators.selected_timezone_is_invalid'
            - '@app.validators.cannot_send_payment_for_the_course_to_which_you_are_not_subscribed_to'
            - '@app.validators.cannot_send_payment_for_the_same_course_again'
            - '@app.validators.cannot_send_payment_for_the_ongoing_or_ended_course'
