blueprint: apiary/api-description.apib
color: true
config: dredd.yml
custom:
  apiaryApiKey: 09e735e86d26111ee3444200fe7fff94
  apiaryApiName: symodbuscencantiogosprespixtra
details: false
dry-run: null
endpoint: 'http://nginx'
header: []
hookfiles: null
hooks-worker-after-connect-wait: 100
hooks-worker-connect-retry: 500
hooks-worker-connect-timeout: 1500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
hooks-worker-term-retry: 500
hooks-worker-term-timeout: 5000
hooks-worker-timeout: 5000
init: true
inline-errors: false
language: php
loglevel: warning
method: []
names: false
only: []
output: []
path: []
reporter: apiary
require: null
server: null
server-wait: 3
sorted: false
user: null
