imports:
    - { resource: config_dev.yaml }

framework:
    test: ~
    #session:
    #    storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

services:

    _defaults:
        autowire: true
        autoconfigure: false
        public: true

    test.client:
        class: Tests\WebClient

    App\EntityFactories\SessionFactory: ~
    App\EntityFactories\UserFactory: ~

    App\Generators\ApiTokenGenerator: ~
    App\Generators\TokenGenerator: ~

    App\Repositories\PaymentRepository: ~

    App\Passwords\PasswordSettings:
        arguments:
            - !php/const App\Passwords\PasswordAlgorithms::BCRYPT
            - 13
            - 4
            - 65536

    Tests\ApiTokenGeneratorWithPredefinedApiToken: ~
    Tests\PasswordSettingsWithPredefinedValues: ~
    Tests\SessionFactoryWithPredefinedApiToken: ~
    Tests\TokenGeneratorWithPredefinedToken: ~
    Tests\UserFactoryWithPredefinedToken: ~
