#!/usr/bin/env php
<?php

declare(strict_types=1);

require __DIR__ . '/../vendor/autoload.php';

echo Nette\Utils\Random::generate(App\Http\ApiHeaders::API_KEY_LENGTH, App\Http\ApiHeaders::API_KEY_PATTERN) . PHP_EOL;
